name: mobile_banking
description: A new Flutter project.

publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  dartz: ^0.10.1
  device_info_plus: ^9.1.0
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.3.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  lottie: ^2.7.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: 11.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  showcaseview: ^2.1.1
  sqflite: ^2.3.0
  flutter_screenutil: ^5.9.3
  package_info: ^2.0.2
  geolocator: ^8.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - .dev.env
    - assets/images/icons/
    - assets/animations/
    - assets/files/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
